import Head from 'next/head'
import Image from 'next/image'
import styles from "../styles/layout.module.css";
import Link from 'next/link'

export default function layout({ children }) {
    return (
        <div className={styles.wrapper}>
            <Head>
                <title>Yelp Roulette App</title>
                <meta name="description" content="Generated by Yelp Roulette app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            {/* Navbar Section */}
            <nav className={styles.nav}>
                <p className={styles.titleLogo}> YR </p>
                <Link href="/">
                    <a> Home </a>
                </Link>
            </nav>

            {/* body */}
            <main>{children}</main>

            {/* Footer Section */}
            <footer className={styles.footer}>
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    <p>Powered by</p>
                    <span className={styles.logo}>
                        <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
                    </span>
                </a>
            </footer>
        </div>
    )
}
